### ISSUE TITLE
How to call a JavaScript function on Menu item click?

### ISSUE THREAD

**Issue by srameh** [ElectronNET/electron.net-api-demos#10]
I need load a different page using ajax from a Menu click. For example I have a FAQ menu item which has its own view. I want to load this on Ajax call. Something similar to openExternal function.
How can this be done?

(function () {
    const shell = require('electron').shell
    const links = document.querySelectorAll('a[href]')

    Array.prototype.forEach.call(links, function (link) {
        const url = link.getAttribute('href')
        if (url.indexOf('http') === 0) {
            link.addEventListener('click', function (e) {
                e.preventDefault()
                shell.openExternal(url)
            })
        }
    })
})

**Comment by GregorBiswanger** [comment]
Comes with the next Electron.NET update.

**Comment by srameh** [comment]
Is this feature available now? If so where can I find an example of it?
