### ISSUE TITLE
cannot run demo project

### ISSUE THREAD

**Issue by ortrails** [ElectronNET/electron.net-api-demos#11]
I have installed dotnet SDK 2.2. Is this possibly the problem?

2019-01-02 13:11:00 astringer@77swprg192 MINGW64 /c/source3/electron.net-api-demos/ElectronNET-API-Demos (master)
$ dotnet restore
  Restoring packages for C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj...
  Restoring packages for C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj...
  Restore completed in 68.84 ms for C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj.
C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj : error NU1202: Package ElectronNET.CLI 0.0.11 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package ElectronNET.CLI 0.0.11 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj : error NU1212: Invalid project-package combination for ElectronNET.CLI 0.0.11. DotnetToolReference project style can only contain references of the DotnetTool type
  Restore failed in 217.81 ms for C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj.
  Generating MSBuild file C:\source3\electron.net-api-demos\ElectronNET-API-Demos\obj\ElectronNET-API-Demos.csproj.nuget.g.props.
  Generating MSBuild file C:\source3\electron.net-api-demos\ElectronNET-API-Demos\obj\ElectronNET-API-Demos.csproj.nuget.g.targets.
  Restore completed in 2.45 sec for C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj.

**Comment by atotalnoob** [comment]
Yes, the stack trace says so. 2.1 is the highest

**Comment by ortrails** [comment]
well, i uninstalled 2.2 and now i get this. 

C:\source3\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj : error NU1202: Package ElectronNET.CLI 0.0.11 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package ElectronNET.CLI 0.0.11 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any

any more ideas?

**Comment by umarafzal1** [comment]
I am facing the same issue and as @ortrails ,
Any suggestions  ?

**Comment by mpconte** [comment]
@umarafzal1 I did the same thing and got it running, but I can't seem to be able to launch any windows via the Windows Controller. I've noticed that it's because **HybridSupport.IsElectronActive** is false throughout the entire demo app. How does this value become true?

**Comment by GregorBiswanger** [comment]
Updatet to .NET Core 3.1 and Electron.NET 8.31.1

**Comment by amigax** [comment]
how do we make HybridSupport.IsElectronActive true?
