### ISSUE TITLE
Issue running demos

### ISSUE THREAD

**Issue by richardpartridgeflynet** [ElectronNET/electron.net-api-demos#12]
Hi,

I'm encountering an issue running the demos on Windows (2012R2). They start fine but, after a variable amount of time, the connection between the Electron UI and the ASP.NET web app appears to break. Once this has happened the UI remains responsive (the buttons etc. are still clickable) but they get no response from the web app. In addition, once the connection is broken, messages like this appear in the console about every 30 seconds or so:
```
ASP.NET Core Application connected... global.electronsocket vftRiQtzjdkYz_5fAAAB 2019-01-08T11:14:01.851Z
stdout: BridgeConnector connected!
```
Does anyone have any suggestions on how to resolve the issue or how to debug what's going on?

Regards,

Richard

**Comment by GregorBiswanger** [comment]
Hi Richard,
this Demos App ist not created with the newest Electron.NET API.
We fixed this problem and publish the next release in a couple of days.

Best,
Gregor
