### ISSUE TITLE
Sometimes Application Runs but will not open Window

### ISSUE THREAD

**Issue by horst-evans** [ElectronNET/electron.net-api-demos#18]
The majority of the time, `electronize start` appears to run, I get a `stdout: BridgeConnector connected!` message, and there is an executable running in task manager, but the application window never appears. Also, if I ctr-c in cmd, I also have to manually end the "ElectronNET-API-Demo.exe" in task manager.

However, I have gotten it to run twice without any issue, and without changing anything on my end, so I am not sure what the cause is.

Here is the output of `electronize start` when it fails to open the app
[output.txt](https://github.com/ElectronNET/electron.net-api-demos/files/3644293/output.txt)

**Comment by dparne** [comment]
Same issue for me. Any ideas?

**Comment by LumiteDubbz** [comment]
https://github.com/ElectronNET/electron.net-api-demos/issues/19 - I created this issue with pretty much the same problem as you, but a restart fixed it for me

**Comment by horst-evans** [comment]
I tried a restart, but it did not seem to fix the issue.

**Comment by dreammaster38** [comment]
The same issue happend to me. The demo application reported "Application started. Press Ctrl+C to shut down." at the end.
There are one process " ElectronNET-API-Demo.exe" and three processes "electron.exe" visible in task manager but there is still no window open.

My System:
Microsoft Windows 10 Enterprise x64 V10.0.17134
.Net Core SDK V3.0.100 RTM

**Comment by burakakca** [comment]
hi i'm coming from 2020, is there a change? what is the solution?

**Comment by GregorBiswanger** [comment]
Hi, I´m from 1990... the internet here is the craziest thing I've ever seen... a good friend of mine works with Doc Brown... I asked him and he said that the latest demo app can be found in the original repository... secret word: WebApp... just clone and run... 

now i have to go back to my decade ... and start with a company called Amazon or something..

**Comment by melramkhelawan** [comment]
Having same issue. Has anyone found a solution? Tried restarting but doesn't help.

**Comment by yawnston** [comment]
@GregorBiswanger so if I understood that comment correctly then the `ElectronNET.WebApp` project in the main `Electron.NET` repo is a more up-to-date version of this project? Seems strange to have the same demo app in two places.

**Comment by GregorBiswanger** [comment]
@yawnston That's right.. I'm currently working on version 8.31.1 - then I'll update the project again here...

**Comment by yawnston** [comment]
Isn't that a little bit impractical to maintain the same project in 2 places? Why not just have the WebApp project here and not in the main repo? I see you are using it to build the app as an artifact in AppVeyor, but surely that is possible for 2 separate repositories as well?

**Comment by GregorBiswanger** [comment]
In the main repo it simplifies my development on the API / host etc. - But yes, in principle this is really very impractical...

**Comment by GregorBiswanger** [comment]
Updated to .NET Core 3.1 and Electron.NET 8.31.1
