### ISSUE TITLE
Application launching in command line, window not opening, tasks not ending

### ISSUE THREAD

**Issue by LumiteDubbz** [ElectronNET/electron.net-api-demos#19]
ElectronNET.CLI version 5.22.14.0
Node version (using NVM for Windows): 8.2.1
dotNet version: Core 2.2.105

Whenever I `cd` into the `electron.net-api-demos` folder and run `electronize start`, I get to the final "`stdout: BridgeConnector connected!`" but no window opens. When I hit CTRL + C to close the application, the 3 Electron and 1 ElectronNET-API-Demos.exe processes stay open and I have to manually close them in Task Manager.

Anyone know if this is my doing or an issue with the application itself? Thanks in advance.

**Comment by LumiteDubbz** [comment]
Turned PC off last night. Turned on this morning and now it's working. Protip: restart first, open issue later.

**Comment by omerfarukz** [comment]
It is not stable.

**Comment by GregorBiswanger** [comment]
@omerfarukz Do you already have the latest version? 11.5.1

**Comment by omerfarukz** [comment]
Thanks for your quick response first. Yes. Followed documentation and executed 'electronize start' at my first attempt at it stuck on splash screen. When I tried again, it works but I tried start and quit sequence more than 10. It happened one or more times again. Tried to kill dotnet process manually but I may happens when there is no dotnet process running in background. There is no error message but bridge connected message is delayed on console. I guess it is waiting for something.

**Comment by omerfarukz** [comment]
I also trying to run this on ubuntu. Main window did not loaded. I tried 3 times. I am using ubuntu 20.04 with Parallels desktop on same host.

![Screen Shot 2021-02-04 at 14 02 18](https://user-images.githubusercontent.com/2807847/106883996-cf89d400-66f1-11eb-974e-719aee86ddb4.png)

**Comment by GregorBiswanger** [comment]
Thanks for your feedback!

Please check whether you have the latest version of the API and CLI 11.5.1.

It is best to delete the Obj folder from your project again beforehand.

Then start once with:
`electronize start / clear-cache`

The sample project here is NOT in the current Electron.NET version.

**Comment by GregorBiswanger** [comment]
Our main repository has the WebApp project. This is the demo app with the current version. I still have to update this repository. Just didn't have time. :)

**Comment by omerfarukz** [comment]
'electronize start / clear-cache' did not solve the issue on ubuntu and mac. This issue is happens even first run.

omr@omr-ubuntu:~/electron.net-api-demos$ electronize version
ElectronNET.CLI Version: 11.5.1.0

Do you have a documentation for bootstrapping from latest version?

**Comment by GregorBiswanger** [comment]
Just try a new ASP.NET Core project with the guidance of:
https://github.com/ElectronNET/Electron.NET

This repository is currently out of date. I will update it the days.

**Comment by omerfarukz** [comment]
Yeah, thank you for your patience. I want to contribute this repo just because of your honesty.
