### ISSUE TITLE
Call custom menu on html element.

### ISSUE THREAD

**Issue by Xarkam** [ElectronNET/electron.net-api-demos#20]
Hello, is it possible with Electron.NET to create a menu called in a manner similar to the one found [here](https://dev.to/saisandeepvaddi/creating-a-custom-menu-bar-in-electron-1pi3) ?

**Comment by GregorBiswanger** [comment]
Please see the source code from the sample app here:
https://github.com/ElectronNET/electron.net-api-demos/blob/master/ElectronNET-API-Demos/Controllers/MenusController.cs
