### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by mertmtn** [ElectronNET/electron.net-api-demos#21]
I have pulled electron.net-api-demos and  I typed electronize start to run project, When I checked developer console, got script error in below files. 

![image](https://user-images.githubusercontent.com/37337606/107885592-4bfb8e80-6f0c-11eb-84c4-5127d30b5b7a.png)

I currently using Node.js 14.15.5

**Comment by mertmtn** [comment]
Maybe there is no class named ".task-template" from link parameter.

![image](https://user-images.githubusercontent.com/37337606/107885808-65e9a100-6f0d-11eb-8624-09b5a2c750c1.png)

**Comment by Gsonovb** [comment]
I also have this problem



According to the error prompt, the import function has been removed in chrome V80.

https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade


[dotnet.txt](https://github.com/ElectronNET/electron.net-api-demos/files/5985969/dotnet.txt)

**Comment by ienaboard** [comment]
Any way/workaround to solve this issue?
