### ISSUE TITLE
Problem running the demo

### ISSUE THREAD

**Issue by APX403** [ElectronNET/electron.net-api-demos#25]
The demo is launching but all button "View Demo" does nothing. I don't see any error in the console of dev tools. 

Am I missing something ?

https://i.ibb.co/z84Xmn5/electronnetdemobug.gif

Thanks

**Comment by zhaobinbin2019** [comment]
same issue with me. 
node version v14.16.0
.net core version 3.1
ElectronNET-API version 8.31.2
it looks like the IPC function not work?

**Comment by scharli** [comment]
Same here, the buttons did not work on mac

**Comment by alifhaikal88** [comment]
> Same here, the buttons did not work on mac

same issue

**Comment by craigfarrell** [comment]
Is anyone looking at this?  None of the buttons do anything...

**Comment by johguentner** [comment]
> Is anyone looking at this? None of the buttons do anything...
@craigfarrell

same Problem here. I'm trying to find the cause, but until now I have not figured it out.

**Comment by nathenxbrewer** [comment]
Same here. UI works but all the 'View Demo' buttons do not.

**Comment by DmitryBolotin** [comment]
Hi guys. You can check this folder. It is pretty the same, but it works -> https://github.com/ElectronNET/Electron.NET/tree/master/ElectronNET.WebApp

**Comment by langyo** [comment]
same issue

**Comment by alan0428a** [comment]
same here

**Comment by AndreyBilalov** [comment]
You need execute electronize start command before starting application.

**Comment by mehran-mousavi** [comment]
> The demo is launching but all button "View Demo" does nothing. I don't see any error in the console of dev tools.
> 
> Am I missing something ?
> 
> https://i.ibb.co/z84Xmn5/electronnetdemobug.gif
> 
> Thanks

Clone https://github.com/mehran-mousavi/electron.net-api-demos & Enjoy
Cheers!

**Comment by rattledoge** [comment]
> Still having start issues. Getting following error;
![Screenshot_1](https://user-images.githubusercontent.com/71441854/175040723-314b15e0-a1b9-426f-997a-ed8861775a92.png)
Running on W10 with .Net Core 6.0.3 SDK and Node.js 18.4

**Comment by mehran-mousavi** [comment]
> > Clone https://github.com/mehran-mousavi/electron.net-api-demos & Enjoy
> > Cheers!
> 
> Still having start issues. Getting following error; ![Screenshot_1](https://user-images.githubusercontent.com/71441854/175040723-314b15e0-a1b9-426f-997a-ed8861775a92.png) Running on W10 with .Net Core 6.0.3 SDK and Node.js 18.4
> 
> @mehran-mousavi

Hey, some improvements and fixes have been done. You may now clone the most recent stable .Net6 demo at:

https://github.com/mehran-mousavi/Electron.net-.Net-6-Demos

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
