### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by julianadormon** [ElectronNET/electron.net-api-demos#26]
Just downloaded solution and can't run demo because of the following errors:
Build:Cannot find namespace 'SocketIO'.
Build:Cannot find module 'exceljs' or its corresponding type declarations.

I downloaded the source code as a zip. Unpacked it and opened the solution in VS 2019. Then tried to build it.

**Comment by lzb949838390** [comment]
> 刚刚下载的解决方案，由于以下错误而无法运行演示：Build：找不到命名空间"SocketIO"。 Build：找不到模块 'exceljs' 或其相应的类型声明。
> 
> 我下载了源代码作为zip。解压缩了它，并在VS 2019中打开了解决方案。然后试图构建它。

I also encountered the same problem. How can I solve it?

> Just downloaded solution and can't run demo because of the following errors: Build:Cannot find namespace 'SocketIO'. Build:Cannot find module 'exceljs' or its corresponding type declarations.
> 
> I downloaded the source code as a zip. Unpacked it and opened the solution in VS 2019. Then tried to build it.

I also encountered the same problem. How can I solve it?

**Comment by lzb949838390** [comment]
> Just downloaded solution and can't run demo because of the following errors: Build:Cannot find namespace 'SocketIO'. Build:Cannot find module 'exceljs' or its corresponding type declarations.
> 
> I downloaded the source code as a zip. Unpacked it and opened the solution in VS 2019. Then tried to build it.

I also encountered the same problem. How can I solve it?

**Comment by JacobCaiC** [comment]
same problem, no one answer

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
