### ISSUE TITLE
Application doesn't started! It is showed splash screen and disapeared.

### ISSUE THREAD

**Issue by paveltkalenko** [ElectronNET/electron.net-api-demos#29]
Last messages in console

```
Got disconnect! Reason: ping timeout
ASP.NET Core Application connected... global.electronsocket fTtjwYi4jGk8JGxJAAAA 2022-04-12T07:46:11.206Z
stdout: BridgeConnector connected!
```
.net core 3.1
nodejs version 17.9.0

**Comment by mehran-mousavi** [comment]
> Last messages in console
> 
> ```
> Got disconnect! Reason: ping timeout
> ASP.NET Core Application connected... global.electronsocket fTtjwYi4jGk8JGxJAAAA 2022-04-12T07:46:11.206Z
> stdout: BridgeConnector connected!
> ```
> 
> .net core 3.1 nodejs version 17.9.0

Clone https://github.com/mehran-mousavi/electron.net-api-demos & Enjoy
Cheers!

**Comment by alelom** [comment]
Same problem here. Never got it to work.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

**Comment by nahuelmiralpeix** [comment]
> 🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉
> 
> With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!

dont work

**Comment by nahuelmiralpeix** [comment]
![image](https://github.com/ElectronNET/electron.net-api-demos/assets/55743203/9c8da32a-bdd8-43ff-bb63-d8cfed2233dd)
dont pass the initial splash screen
