### ISSUE TITLE
I Can't Take It Work?

### ISSUE THREAD

**Issue by DarrenWen** [ElectronNET/electron.net-api-demos#3]
When I Run The App,It's Errors:
C:\Users\darren\core\electron.net-api-demos\ElectronNET-API-Demos\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\Users\darren\core\electron.net-api-demos\ElectronNET-API-Demos\obj\Host\node_modules\electron\cli.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by GregorBiswanger** [comment]
Hi @DarrenWen,
remove the Host folder from obj folder and tray again please.
