### ISSUE TITLE
Notification icon not showing

### ISSUE THREAD

**Issue by Nyalothas** [ElectronNET/electron.net-api-demos#4]
The notification icon with image is not showing any image.
Tried to set a different path, different image type(ico), no extension, server path, nothing.
I can access the image directly in a browser, but the notification won't show any.

The [Docs](https://github.com/electron/electron/blob/v1.7.8/docs/api/notification.md) says that it requires a Native Image, but the NativeImage class is empty. So I guess that it's not yet implemented? Thanks!

Using Windows 7 Version 6.1 Build 7601: SP1 x64
Edit: Tested on Windows 10 and same issue

**Comment by GregorBiswanger** [comment]
That is a native Electron bug:
https://github.com/electron/electron/issues/10864

but I will try to fix it, for the next Electron.NET update with a workaround...
