### ISSUE TITLE
Suggestion: Add release with prebuilt binaries

### ISSUE THREAD

**Issue by InDieTasten** [ElectronNET/electron.net-api-demos#7]
That way, trying the demo wouldn't require people to install node version 8 and the core sdk.

It would also demonstrate what a "shipped" application would look like, and prove that the demo can run without SDKs installed.

**Comment by GregorBiswanger** [comment]
You need for build the binaries the node.js.. and this binaries working without installed node.js.

**Comment by InDieTasten** [comment]
I know that. It's been a while since I've skimmed over this repo. I know, that you need node.js to build the binaries.

My suggestion was (since this repo is consisting of sample/demo applications) to actually create "GitHub releases" with the binaries of the sample applications prebuilt. This way, people can try the sample applications (their look and feel), without personally having to clone, figure out the correct node/npm version, npm install, figure out how to run the samples and so on.

They could just download the binaries for their platform, run them and get the result. It would also show how shipping applications looks like, how big of a download these are and so on. Those are important aspects for people trying to evaluate whether a platform/framework is worth digging into further.

**Comment by GregorBiswanger** [comment]
With the next Electron.NET update there will be an AutoUpdate function ... Then you can download here the release binaries (With clickonce installer ;) )... Then only for Windows and Linux ... For Mac I have no device and certificate. .. Do you like that?

**Comment by InDieTasten** [comment]
That sounds great. I no longer need this myself, but I think this will be useful for many others stumbling across this repo.
