### ISSUE TITLE
ElectronNET-API-Demos.dll is being used by another process

### ISSUE THREAD

**Issue by jaykannan** [ElectronNET/electron.net-api-demos#8]
Running the project outright in VS Code on Windows using `dotnet electronize start` causes this issue and I can't seem to figure out why. it ran the first time and has been doing this since then. I deleted bin/obj folders and it didn't help. how do I generally fight this?

> C:\Program Files\dotnet\sdk\2.1.104\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(137,5): warning MSB3026: Could not copy "obj\Debug\netcoreapp2.0\win-x64\ElectronNET-API-Demos.dll" to "C:\Users\jayde\Documents\Projects\electron.net-api-demos\ElectronNET-API-Demos\obj\Host\bin\ElectronNET-API-Demos.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Users\jayde\Documents\Projects\electron.net-api-demos\ElectronNET-API-Demos\obj\Host\bin\ElectronNET-API-Demos.dll' because it is being used by another process.  [C:\Users\jayde\Documents\Projects\electron.net-api-demos\ElectronNET-API-Demos\ElectronNET-API-Demos.csproj]

**Comment by mohchari** [comment]
I've had this happen before. Did you check the running processes? I've noticed electron not actually closing. Same with the exe. I'm not sure if this is an issue specific to this demo, or just a bug in general though.

**Comment by GregorBiswanger** [comment]
An existing Electron.NET instance was active.. kill this process yourself ... and start again... the next Electron.NET update should fixed it..

**Comment by win32nipuh** [comment]
I have received the same error
